# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Self-hosted
  
jobs:
- job: echo_message
  displayName: 'Echo Message'
  pool:
    name: 'Self-hosted'
  steps:
  - script: |
      echo "Starting the SAST scan job..."
    displayName: 'Echo Message'

- job: sast_scan
  displayName: 'Run Bandit Scan'
  pool:
    name: 'Self-hosted'
  steps:
  - script: |
      export NODE_TLS_REJECT_UNAUTHORIZED=0
    displayName: 'Disable SSL Verification'

  - script: |
      export PATH=$PATH:/usr/local/bin/python3.13:/Library/Frameworks/Python.framework/Versions/3.13/bin
      python3.13 -V
      python3.13 -m pip install --upgrade pip
      python3.13 -m pip --version
    displayName: 'Set up Python 3.13.1 and pip'

  - script: |
      source ~/myagent/_work/_tool/Python/3.13.1/x64/bin/activate
      bandit --version
      deactivate
    displayName: 'Verify Bandit Installation'

  - script: |
      source ~/myagent/_work/_tool/Python/3.13.1/x64/bin/activate
      bandit -ll -ii -r . -f json -o bandit-report.json
      deactivate
    displayName: 'Run Bandit Scan'


  - task: PublishBuildArtifacts@1
    displayName: 'Upload Artifact'
    inputs:
      PathtoPublish: 'bandit-report.json'
      ArtifactName: 'bandit-findings'
      publishLocation: 'Container'

  # - task: UsePythonVersion@0 
  #   displayName: 'Set up Python'
  #   inputs:
  #     versionSpec: '3.13.1'
  #     addToPath: true
  #     disableDownloadFromRegistry: true

