# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Self-hosted
  
jobs:
- job: echo_message
  displayName: 'Echo Message'
  pool:
    name: 'Self-hosted'
  steps:
  - script: |
      echo "Starting the SAST scan job..."
    displayName: 'Echo Message'

- job: sast_scan
  displayName: 'Run Bandit Scan'
  pool:
    name: 'Self-hosted'
  steps:
  - task: Checkout@2
    displayName: 'Checkout code'

  - task: UsePythonVersion@0
    displayName: 'Set up Python'
    inputs:
      versionSpec: '3.8'

  - script: |
      pip install bandit
    displayName: 'Install Bandit'

  - script: |
      bandit -ll -ii -r . -f json -o bandit-report.json
    displayName: 'Run Bandit Scan'

