# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Self-hosted
  
jobs:
- job: echo_message
  displayName: 'Echo Message'
  pool:
    name: 'Self-hosted'
  steps:
  - script: |
      echo "Starting the SAST scan job..."
    displayName: 'Echo Message'

- job: sast_scan
  displayName: 'Run Bandit Scan'
  pool:
    name: 'Self-hosted'
  steps:
  - script: |
      export NODE_TLS_REJECT_UNAUTHORIZED=0
    displayName: 'Disable SSL Verification'
    
  - task: UsePythonVersion@0
    displayName: 'Set up Python'
    inputs:
      versionSpec: '3.13.1'
      addToPath: true
      disableDownloadFromRegistry: true

  - script: $(pyTools.pythonLocation)/bin/pip install --upgrade tox
    displayName: Install Python-based tools.

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
    displayName: Use cached Python $(python.version) for tests.
      
  - script: |
      pip install bandit
    displayName: 'Install Bandit'

  - script: |
      bandit -ll -ii -r . -f json -o bandit-report.json
    displayName: 'Run Bandit Scan'

