name: CI

on: [push]

jobs:
 sast_scan:
   name: Run Bandit Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Set up Python
     uses: actions/setup-python@v5
     with:
       python-version: 3.8

   - name: Install Bandit
     run: pip install bandit

   - name: Run Bandit Scan
     run: bandit -ll -ii -r . -f json -o bandit-report.json
    
   - name: Upload Artifact
     uses: actions/upload-artifact@v4
     if: always()
     with:
      name: bandit-findings
      path: bandit-report.json
      
   - name: Defectdojo Import Report
     uses: portswigger-cloud/defectdojo-import-scan@v1.0.1
     if: always()
     with:
      defectdojo-url: 172.210.46.36:8080
      defectdojo-username: ${{ secrets.DEFECTDOJO_USER }}
      defectdojo-password: ${{ secrets.DEFECTDOJO_PASS }}
      defectdojo-product-type: Research and Development
      defectdojo-product: Test Dashboard
      defectdojo-environment-type: Development
      defectdojo-scan-type: SAST Scan
      defectdojo-engagement-name: pygoat-github
      scan-results-file-name: bandit-report

   - name: DefectDojo Import scan
     # You may pin to the exact commit or the version.
     # uses: ivanamat/defectdojo-import-scan@a5865a5c30dabc66736603bbded081941b9c07ea
     uses: ivanamat/defectdojo-import-scan@v1
     if: always()
     with:
      token: 3403b5b01ff4e8b9628e82a75efa94e22be91624
      # (string) The DefectDojo base url. Example: https://defectdojo.domain.com
      defectdojo_url: 172.210.46.36:8080
      scan_type: SAST Scan
      file: bandit-report
      engagement: pygoat-github


 image_scan:
  name: Build image & run Scan
  runs-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Setup Docker
    uses: docker-practice/actions-setup-docker@v1
    with:
     docker_version: '20.10.7'

  - name: Build docker image
    run: docker build -f Dockerfile -t myapp:latest --progress=plain .

  # - name: Docker Scout Scan
  #   run: |
  #       curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
  #       sh install-scout.sh

  #       echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
        
  #       docker scout quickview
  #       docker scout cves

  - name: Docker Scout Scan
    uses: docker/scout-action@v1.16.1
    with:
     dockerhub-user: ${{ secrets.DOCKERHUB_USER }}
     dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
     command: quickview, cves
     only-severities: critical, high
     sarif-file: docker-scout-report.sarif
     exit-code: true

  - name: Upload Artifact
    uses: actions/upload-artifact@v4
    if: always()
    with:
      name: docker-scout-findings
      path: docker-scout-report.sarif

  - name: Defectdojo Import Report
    uses: portswigger-cloud/defectdojo-import-scan@v1.0.1
    if: always()
    with:
      defectdojo-url: 172.210.46.36:8080
      defectdojo-username: ${{ secrets.DEFECTDOJO_USER }}
      defectdojo-password: ${{ secrets.DEFECTDOJO_PASS }}
      defectdojo-product-type: Research and Development
      defectdojo-product: Test Dashboard
      defectdojo-environment-type: Development
      defectdojo-scan-type: Container Scan
      defectdojo-engagement-name: pygoat-github
      scan-results-file-name: docker-scout-report
     
     
